language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: Cvt/brcSMMsKNRPZ0jbtxIq/SWxrPb2PZV3N2HerElf7GnxpmrfFOKgkRv+W6AZsnVlf+HKLsFit7nTsMuzpnRg4eOCTDQ5za58q7k4cRWQ64jXvaeX6i4r3ecubET4qMtJU7ugkRGBt3psPnNBHpRdB90HbYJYhv+KXcLIRNFHLrNUsauPubLluOSKIrXFC7tmGgQTo0ekCPhpgSQ3V6ZdMhKT8q/uU68Yfc1WizXaLxHfRG3c5l/H89sDo7KJ5DLatRpZo0Dcju+gmZVmwMmPikcaNOhLj+e2LKC32msayo2gpNDvsvGs6qbon48gQiBj4cPk8XXGsReSmrdnXqCKy1iDY9gePLOEeMQjxh7+6FZlQMPq7ukRK84s4T/xu/hTDSsJx6PNfSOAJsansA7ZySuIqH9vteOCr0mIwnpISUEOFBXGLVQBrDfr96aUILtw0i6WHLyWrpN8q9IsTf7XcEoiwGDAEkuU+K4+2eNTvlLQfK5Jwg8It9IFspfF0iVI1LssaI6pv2mYtbJaPpgcfB2FlFqCeTkoUUG1EGOfqm+A2arNsnUqR8O+HnbMPqGnJ6cfyedxD7Wb2U2O3ntFwwf9Am1WbGMsIU3o8kxTwdsjTWMIRZ9Iv7rG9RteYEBSLt2F0Zy6h2thE4Yx5WuGfZm5KKGHVv0HqDDYvciA=
